allowBuilds:
<<<<<<< HEAD
  '@parcel/watcher': set this to true or false
  unrs-resolver: set this to true or false
  vue-demi: set this to true or false
=======
  '@parcel/watcher': true
  unrs-resolver: true
  vue-demi: true
>>>>>>> 24c09dd0d2e3a345ced6bd6449ff0c89cd686543
